# Generated by Django 4.0.5 on 2023-02-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
    ]
